// Mocks generated by Mockito 5.4.6 from annotations
// in xflow/test/features/profile/profile_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:xflow/core/client/twitter_client.dart' as _i2;
import 'package:xflow/core/database/entities.dart' as _i4;
import 'package:xflow/core/models/tweet.dart' as _i6;
import 'package:xflow/features/settings/settings_provider.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTweetResponse_0 extends _i1.SmartFake implements _i2.TweetResponse {
  _FakeTweetResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TwitterClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockTwitterClient extends _i1.Mock implements _i2.TwitterClient {
  MockTwitterClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Subscription?> fetchProfile(String? screenName) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchProfile,
          [screenName],
        ),
        returnValue: _i3.Future<_i4.Subscription?>.value(),
      ) as _i3.Future<_i4.Subscription?>);

  @override
  _i3.Future<_i2.TweetResponse> fetchUserTweets(
    String? screenName, {
    String? cursor,
    _i5.FeedSort? sort,
    Set<_i5.MediaFilter>? filters,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchUserTweets,
          [screenName],
          {
            #cursor: cursor,
            #sort: sort,
            #filters: filters,
          },
        ),
        returnValue: _i3.Future<_i2.TweetResponse>.value(_FakeTweetResponse_0(
          this,
          Invocation.method(
            #fetchUserTweets,
            [screenName],
            {
              #cursor: cursor,
              #sort: sort,
              #filters: filters,
            },
          ),
        )),
      ) as _i3.Future<_i2.TweetResponse>);

  @override
  _i3.Future<List<_i4.Subscription>> fetchFollowing(
    String? userId, {
    int? maxCount = 2000,
    int? cooldownMinutes = 15,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchFollowing,
          [userId],
          {
            #maxCount: maxCount,
            #cooldownMinutes: cooldownMinutes,
          },
        ),
        returnValue:
            _i3.Future<List<_i4.Subscription>>.value(<_i4.Subscription>[]),
      ) as _i3.Future<List<_i4.Subscription>>);

  @override
  _i3.Future<_i2.TweetResponse> fetchTrendingMedia({
    String? cursor,
    String? query,
    _i5.FeedSort? sort,
    Set<_i5.MediaFilter>? filters,
    int? count = 20,
    int? cooldownMinutes = 15,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchTrendingMedia,
          [],
          {
            #cursor: cursor,
            #query: query,
            #sort: sort,
            #filters: filters,
            #count: count,
            #cooldownMinutes: cooldownMinutes,
          },
        ),
        returnValue: _i3.Future<_i2.TweetResponse>.value(_FakeTweetResponse_0(
          this,
          Invocation.method(
            #fetchTrendingMedia,
            [],
            {
              #cursor: cursor,
              #query: query,
              #sort: sort,
              #filters: filters,
              #count: count,
              #cooldownMinutes: cooldownMinutes,
            },
          ),
        )),
      ) as _i3.Future<_i2.TweetResponse>);

  @override
  _i3.Future<_i2.TweetResponse> fetchSubscribedMedia({
    String? cursor,
    _i5.FeedSort? sort,
    Set<_i5.MediaFilter>? filters,
    int? subBatchSize = 10,
    int? loadBatchSize = 20,
    int? cooldownMinutes = 15,
    bool? strictSubscriptionsOnly = true,
    bool? includeNativeRetweets = false,
    bool? useChunkedSubscriptions = true,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchSubscribedMedia,
          [],
          {
            #cursor: cursor,
            #sort: sort,
            #filters: filters,
            #subBatchSize: subBatchSize,
            #loadBatchSize: loadBatchSize,
            #cooldownMinutes: cooldownMinutes,
            #strictSubscriptionsOnly: strictSubscriptionsOnly,
            #includeNativeRetweets: includeNativeRetweets,
            #useChunkedSubscriptions: useChunkedSubscriptions,
          },
        ),
        returnValue: _i3.Future<_i2.TweetResponse>.value(_FakeTweetResponse_0(
          this,
          Invocation.method(
            #fetchSubscribedMedia,
            [],
            {
              #cursor: cursor,
              #sort: sort,
              #filters: filters,
              #subBatchSize: subBatchSize,
              #loadBatchSize: loadBatchSize,
              #cooldownMinutes: cooldownMinutes,
              #strictSubscriptionsOnly: strictSubscriptionsOnly,
              #includeNativeRetweets: includeNativeRetweets,
              #useChunkedSubscriptions: useChunkedSubscriptions,
            },
          ),
        )),
      ) as _i3.Future<_i2.TweetResponse>);

  @override
  _i3.Future<_i2.TweetResponse> fetchUserTimeline(
    String? userId, {
    String? cursor,
    int? cooldownMinutes = 15,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchUserTimeline,
          [userId],
          {
            #cursor: cursor,
            #cooldownMinutes: cooldownMinutes,
          },
        ),
        returnValue: _i3.Future<_i2.TweetResponse>.value(_FakeTweetResponse_0(
          this,
          Invocation.method(
            #fetchUserTimeline,
            [userId],
            {
              #cursor: cursor,
              #cooldownMinutes: cooldownMinutes,
            },
          ),
        )),
      ) as _i3.Future<_i2.TweetResponse>);

  @override
  _i3.Future<_i2.TweetResponse> fetchUserTimelineByScreenName(
    String? screenName, {
    String? cursor,
    int? cooldownMinutes = 15,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchUserTimelineByScreenName,
          [screenName],
          {
            #cursor: cursor,
            #cooldownMinutes: cooldownMinutes,
          },
        ),
        returnValue: _i3.Future<_i2.TweetResponse>.value(_FakeTweetResponse_0(
          this,
          Invocation.method(
            #fetchUserTimelineByScreenName,
            [screenName],
            {
              #cursor: cursor,
              #cooldownMinutes: cooldownMinutes,
            },
          ),
        )),
      ) as _i3.Future<_i2.TweetResponse>);

  @override
  void parseTweetResult(
    Map<String, dynamic>? itemContent,
    String? entryId,
    List<_i6.Tweet>? tweets,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #parseTweetResult,
          [
            itemContent,
            entryId,
            tweets,
          ],
        ),
        returnValueForMissingStub: null,
      );
}
